# Generated by Django 5.1.4 on 2024-12-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='value',
            field=models.FloatField(),
        ),
    ]
