# Generated by Django 5.1.4 on 2024-12-11 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0002_alter_dataentry_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_visible', models.BooleanField()),
                ('vertex_count', models.IntegerField()),
                ('uv_channel_count', models.IntegerField()),
                ('child_count', models.IntegerField()),
                ('layer_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_name', models.CharField(max_length=255)),
                ('scene_size_kb', models.FloatField()),
                ('timestamp', models.BigIntegerField()),
                ('image', models.URLField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='DataEntry',
        ),
        migrations.AddField(
            model_name='geometry',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geometries', to='webserver.scene'),
        ),
    ]
