# Generated by Django 5.1.4 on 2024-12-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0005_alter_scene_image_alter_scene_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geometry',
            name='child_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geometry',
            name='is_visible',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geometry',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='geometry',
            name='uv_channel_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geometry',
            name='vertex_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scene',
            name='timestamp',
            field=models.FloatField(),
        ),
    ]
